main feature of Currency Exchange
andrey-gumen/CryptoExchange pull request #1
Opened 2022-10-10 12:54 UTC by andrey-gumen

2022-10-10 13:50 UTC, mishamorochko requested changes

2022-10-10 13:50 UTC, mishamorochko commented on CryptoExchange/ViewController.swift
> +class ViewController: UIViewController {
final?

2022-10-10 13:50 UTC, mishamorochko commented on CryptoExchange/ViewController.swift
> +extension Collection {
Расширения для стандартной библиотеки лучше выносить в отдельный файл Collection+Extension или Collection+назвние_того_что_добавил

2022-10-10 13:50 UTC, mishamorochko commented on CryptoExchange/CurrencyViewTable/CurrencyTableViewCell.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
Желательно удалять методы, которые не используются

2022-10-10 19:27 UTC, andrey-gumen commented on CryptoExchange/ViewController.swift
> +class ViewController: UIViewController {
добавил

2022-10-10 19:28 UTC, andrey-gumen commented on CryptoExchange/ViewController.swift
> +extension Collection {
принято, вынес в отдельный файл

2022-10-10 19:28 UTC, andrey-gumen commented on CryptoExchange/CurrencyViewTable/CurrencyTableViewCell.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
удалил

2022-10-17 07:57 UTC, mishamorochko approved these changes

2022-10-17 09:08 UTC, merged